[package]
name = "kadnet"
version = "0.1.0"
edition = "2024"

[dependencies]
cryptal = { git = "https://github.com/Nebula-ecosystem/Cryptal" }
cadentis = { git = "https://github.com/Nebula-ecosystem/Cadentis", package = "cadentis" }