[package]
name = "kadnet-core"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
cryptography = { git = "https://github.com/enzoblain/Cryptography" } 

[dev-dependencies]
tokio = { version = "1", features = ["full"] }