[package]
name = "kadnet-core"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
cryptal = { git = "https://github.com/Nebula-ecosystem/Cryptal" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }